[workspace]
members = [
  "crates/diagnosis",
  "crates/span",
  "crates/syntax",
  "crates/syntax/syntax_derive",
  "fuzz/mu-fuzz-cli",
]


[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
